dist: bionic
language: node_js
node_js:
  - 11
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli@0.3.x
before_script:
  - npm install -g
script:
  - forkfolio build k4ustu3h -f -t dark -i K_ -c k4ustu3h -d k4ustu3h -C k4ustu3h#5045 -e k4ustu3h@gmail.com -F k4ustu3h -I k4ustu3h -k k4ustu3h -m k4ustu3h -P k4ustu3h -n k4ustu3h -r kaustubhladiya -S k4ustu3h -E 16727002 -a k4ustu3h -T k4ustu3h -V 1B8ed -u k4ustu3h -w k4ustu3h -W k4ustu3h -x 9461231 -y UCD79rV3UKNzMCkwMLgyteEw
  - npm run prettier
after_success:
  - lhci autorun --upload.target=temporary-public-storage
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  cleanup: false
  edge: true # opt in to dpl v2
  local_dir: dist
  verbose: true
  fqdn: k4ustu3h.cf
  repo: k4ustu3h/k4ustu3h.cf
  target-branch: gh_pages
