name: Node.js Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: chmod +x bin/forkfolio.js
      - run: npm ci
      - run: npm run test
      - run: npm run prettier

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Build Files
          path: dist/
